# Introduction to Keras - A simple deterministic process

We start with loading the necessary packages.

In [2]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense

I will generate a series that repeats a particular sequence of numbers. This sequence is the following.

In [3]:
Series000=np.array([4,3,5,1,2])
print(Series000)

[4 3 5 1 2]


In [4]:
Series = Series000
for n in range(100):
    Series = np.append(Series, Series000)

print("The head of the series is", Series[:6,])
print("The tail of the series is", Series[-6:,])

print("The length of the series is", len(Series))

The head of the series is [4 3 5 1 2 4]
The tail of the series is [2 4 3 5 1 2]
The length of the series is 505


We will now define the independent variable (X) and the dependent variable (Y).
X(i) represents the present observation and Y(i) represents the next observation.

In [5]:
X=Series[:-1]
Y=Series[1:]

print("X starts", X[:6,])
print("Y starts", Y[:6,])

print("The length of X", len(X))
print("The length of Y", len(Y))


X starts [4 3 5 1 2 4]
Y starts [3 5 1 2 4 3]
The length of X 504
The length of Y 504


In the following, we will generate the neural network model.

In [6]:
model = Sequential([
    Dense(units=16, input_shape=(1,), activation='relu'),
    Dense(units=32, activation='relu'),
    Dense(units=1, activation='linear')
])

The activation function in the last layer needs to maintain the charcteristics of the desired output. Here we are interested in numbers 1, 2, 3, 4, 5.
We could use relu or linear. However, we cannot use sigmoid because the output would be between 0 and 1.
Laterwe will learn how to scale/rescale input and output data.

In the following line, do not forget the parantheses after `summary()`.

In [7]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 16)                32        
_________________________________________________________________
dense_2 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 33        
Total params: 609
Trainable params: 609
Non-trainable params: 0
_________________________________________________________________


In [8]:
model.compile(optimizer='adam', loss='mean_squared_error', metrics=['accuracy'])

In [10]:
model.fit(X, Y, epochs=10, batch_size=1)

Epoch 1/10
504/504 [==============================] - 0s 728us/step - loss: 0.0074 - accuracy: 1.0000
Epoch 2/10
504/504 [==============================] - 0s 732us/step - loss: 9.9678e-04 - accuracy: 1.0000
Epoch 3/10
504/504 [==============================] - 0s 718us/step - loss: 6.6724e-05 - accuracy: 1.0000
Epoch 4/10
504/504 [==============================] - 0s 752us/step - loss: 2.1226e-06 - accuracy: 1.0000
Epoch 5/10
504/504 [==============================] - 0s 669us/step - loss: 2.7717e-08 - accuracy: 1.0000
Epoch 6/10
504/504 [==============================] - 0s 658us/step - loss: 4.1888e-10 - accuracy: 1.0000
Epoch 7/10
504/504 [==============================] - 0s 668us/step - loss: 6.0246e-11 - accuracy: 1.0000
Epoch 8/10
504/504 [==============================] - 0s 695us/step - loss: 1.6507e-13 - accuracy: 1.00000s - loss: 1.6133e-13 - accu
Epoch 9/10
504/504 [==============================] - 0s 671us/step - loss: 1.3730e-13 - accuracy: 1.0000
Epoch 10/10
504/504 [=

We do not really need many epochs for this simple time series.
The loss is Zero and the Accurasy is 100% after few epochs.

**By the way:** Try to run the previos code, i. e. `model.fit` one more time. What do you recognize?

Let us now evaluate the model. I will generate a new series from the original series.
More precisely, I will cut out a random piece from the series above.
First I will import a new library.

In [11]:
from random import randint

In [12]:
start=randint(0,len(Series)-10)
NewSeries=Series[start:start+10]
NewX=NewSeries[0:-1]
NewY=NewSeries[1:]
print(NewX)
print(NewY)

[4 3 5 1 2 4 3 5 1]
[3 5 1 2 4 3 5 1 2]


In [13]:
_, accuracy = model.evaluate(NewX, NewY)
print('Accuracy: %.2f' % (accuracy*100))

9/9 [==============================] - 0s 2ms/step
Accuracy: 100.00


Now let us look at the predictions of this model.
We will make the predictions based on `NewX`. We know from the accuracy before, that we should make correct predictions.

In [14]:
PredictY = model.predict(NewX)
print(PredictY)

[[2.9999995 ]
 [5.        ]
 [0.99999976]
 [2.0000002 ]
 [3.9999998 ]
 [2.9999995 ]
 [5.        ]
 [0.99999976]
 [2.        ]]


As we see, we should round the numbers:

In [15]:
PredictY=np.round(PredictY,0)
print(PredictY)

[[3.]
 [5.]
 [1.]
 [2.]
 [4.]
 [3.]
 [5.]
 [1.]
 [2.]]


Let us also compare the predictions with the true observations.

In [16]:
for i in range(len(PredictY)):
	print('%s => %d' % (NewY[i], PredictY[i]))

3 => 3
5 => 5
1 => 1
2 => 2
4 => 4
3 => 3
5 => 5
1 => 1
2 => 2


## What is next?

1. We should add some noise to this time series.
1. We should add some non-linearity to this time series.
1. How about considering an autoregressive pocesses.
1. We should also look at scaling/rescaling.
1. We should go into separating data into training and test data.

# END